### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by SamuelMarks** [davetron5000/oc#1]
Hey Dave,

Like this project! - Any chance for maintenance?

Namely interested in bumping Ruby version and renaming rubygem name (conflict with DigitalOcean: https://rubygems.org/gems/oc).

**Comment by davetron5000** [comment]
I actually have not ended up using this.  Never released it to RubyGems so if you want to fork it and own it, I can update this with a link to your fork?

**Comment by SamuelMarks** [comment]
Thanks, but I ended up using https://github.com/BrightShadow/orgchart.svg

(with very minor changes)
